import type { Metadata } from 'next';
import './globals.css';
import Navbar from '@/components/navbar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div id="scrab-app">
          <header className="sticky top-0 w-full bg-[#252c33]">
            <Navbar />
          </header>
          {children}
        </div>
        <footer className="mt-8"></footer>
      </body>
    </html>
  );
}
